import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, FileText } from 'lucide-react';
import './PrivacyPolicyPage.css'; // Reuse common legal page styling

export default function TermsPage() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="legal-page-container">
      {/* Breadcrumb nav */}
      <div className="breadcrumb-nav">
        <Link to="/" className="back-link">
          <ArrowLeft size={13} />
          <span>Back to Home</span>
        </Link>
        <span className="crumb-separator">/</span>
        <span className="crumb-current">Terms & Conditions</span>
      </div>

      <div className="legal-content-card glass-panel">
        <header className="legal-header">
          <div className="legal-badge-wrap">
            <FileText size={16} className="legal-icon" />
            <span className="legal-badge">// SERVICE AGREEMENTS REGISTER</span>
          </div>
          <h1 className="legal-title text-gradient">Terms & Conditions</h1>
          <p className="legal-date">LAST UPDATED: JUNE 26, 2026</p>
        </header>

        <div className="legal-sections">
          <section className="legal-section-block">
            <h3>1. Scope of Engagement</h3>
            <p>
              NKXUS Pvt Ltd provides elite digital engineering consulting, web development, custom software configuration, performance marketing, reputation management analytics, and related digital network properties hosting services.
            </p>
          </section>

          <section className="legal-section-block">
            <h3>2. Developer Alignment Requests</h3>
            <p>
              Submitting an initialization parameter form on our platform constitutes a request for feasibility review. No binding contractual obligations are established until a formal statement of work is agreed upon and executed by authorized NKXUS Pvt Ltd engineers.
            </p>
          </section>

          <section className="legal-section-block">
            <h3>3. Proprietary Rights & Licensing</h3>
            <p>
              All layouts, code libraries, vector graphics, custom styles, and modular structures generated by NKXUS Pvt Ltd prior to project handover remain the intellectual property of NKXUS Pvt Ltd. Source code ownership transfer parameters are governed by individual client service level agreements (SLAs).
            </p>
          </section>

          <section className="legal-section-block">
            <h3>4. Limitation of Service Guarantees</h3>
            <p>
              Web design and marketing configurations are delivered under professional standards. NKXUS Pvt Ltd makes no legal representations, warrants, or guarantees concerning third-party software updates, search engine algorithm changes (SEO ranks fluctuation), or server uptime of external network endpoints.
            </p>
          </section>

          <section className="legal-section-block">
            <h3>5. Termination of Usage</h3>
            <p>
              We reserve the right to restrict access to our network portals, codebases, or services systems in the event of billing breaches, usage of services for unlawful activities, or unauthorized attempts to scrape database telemetry registers.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
